server:
  host: localhost
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/testdb
    username: debashis
    password: password

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true